platform :ios, '9.0'

target 'sport’ do

pod 'AFNetworking', '~> 3.1.0'

pod 'IQKeyboardManager'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'Masonry', '~> 1.0.1'
pod 'MJRefresh'
pod 'SDWebImage', '~> 3.7.6'
pod 'Reachability', '~> 3.2'
pod 'SVProgressHUD'
pod 'JSONModel'
end

